name: Java with Maven and AWS

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    - name: Zip JAR file
      run: |
        cd target 
        aws s3 cp aws-lambda-demo-1.0-SNAPSHOT.jar s3://java-lambda-s3

    - name: Upload ZIP to S3
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
    - run: |
        cd target 
        aws s3 cp aws-lambda-demo-1.0-SNAPSHOT.jar s3://java-lambda-s3

   
